module: default
version: 1
runtime: custom
#runtime: python27
vm: true
api_version: 1
threadsafe: yes
manual_scaling:
  instances: 1
vm_settings:
  #machine_type: n1-standard-2
  machine_type: f1-micro

#handlers:
#- url: .*
#  script: main.app




